feature: New tab page
bwinton/whimsy pull request #153
Opened 2017-05-30 18:31 UTC by dnarcese

2017-05-30 18:57 UTC, bwinton requested changes
It works pretty nicely, but there are a few things I'd like to see changed before we merge it.  :smile:

2017-05-30 18:57 UTC, bwinton commented on newtab-page/newtab.html
> +      <iframe src="https://duckduckgo.com/search.html?prefill=Search DuckDuckGo&focus=yes" style="display: block;overflow:hidden;margin: auto;padding:0;width:551px;height:40px;" frameborder="0"></ifr
I feel like the `&` should probably be an `&amp;` for historical reasons…

2017-05-30 18:57 UTC, bwinton commented on bundle.js
> +(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code
Where did this come from?  It seems kinda big…

2017-05-30 18:57 UTC, bwinton commented on scripts/newtab.js
> +    for (let topSite of topSitesArray) {
So, on first run, I only see seven or eight top sites, and they're centered which looks kind of odd…  Could we maybe use [a grid layout](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout/Basic_Concepts_of_Grid_Layout) to make things line up better?  (I think `grid-auto-columns` and `grid-auto-rows` will help with this…)

2017-05-30 18:57 UTC, bwinton commented on scripts/newtab.js
> +            "<span class='newtab-thumbnail thumbnail' style='background-size: cover; background-image: ;'></span>"+
We should really also add [a contextmenu item](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/contextMenu) to let people copy the thumbnail url.  (It was one of our most requested features!)

2017-05-30 18:57 UTC, bwinton commented on scripts/newtab.js
> +  fetch(url).then(function(response){
So, this is the second place we have code like this, if I remember correctly.  Can we extract it into a utility function in another file?

2017-05-30 18:57 UTC, bwinton commented on scripts/newtab.js
> +var getting = browser.storage.sync.get('newtab');
Let's save this into a pref, like in the PR I submitted a couple of days ago…

2017-05-30 18:57 UTC, bwinton commented on scripts/newtab.js
> +          //set gifs
This looks like a lot of code, let's pull it out into a function.

2017-05-30 18:57 UTC, bwinton commented on scripts/newtab.js
> +    querying.then((tabs) => {
Maybe we should only reload the tabs if they're `about:newtab` (or whatever our moz-extension newtab url is)?

2017-05-30 19:04 UTC, dnarcese commented on bundle.js
> +(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code
browserify created that

2017-05-30 19:33 UTC, bwinton commented on bundle.js
> +(function e(t,n,r){function s(o,u){if(!n[o]){if(!t[o]){var a=typeof require=="function"&&require;if(!u&&a)return a(o,!0);if(i)return i(o,!0);var f=new Error("Cannot find module '"+o+"'");throw f.code
I think I'd prefer we included something in a package.json file, and ran browserify as part of a build script.

2017-06-01 19:19 UTC, dnarcese commented
Some changes are taking too long, will come back to them at a later time.

Issue #154

2017-07-04 18:01 UTC, ericawright approved these changes

2017-07-04 18:01 UTC, ericawright commented on scripts/newtab.js
> +// initialize('https://bwinton.github.io/whimsy/thumbnail-gifs.txt')
nit: remove commented code

2017-07-04 18:01 UTC, ericawright commented on scripts/newtab.js
> +  //.then(setThumbnail(placeholders));
also here

2017-07-04 18:05 UTC, merged