add new webextension experiments api to optionally override the new t…
bwinton/whimsy pull request #162
Opened 2018-05-11 18:54 UTC by ericawright

…ab page
![screen shot 2018-05-11 at 2 53 48 pm](https://user-images.githubusercontent.com/10803178/39941622-254d4d3a-552b-11e8-86cd-5462dd609256.png)
![screen shot 2018-05-11 at 2 53 42 pm](https://user-images.githubusercontent.com/10803178/39941623-2642ca30-552b-11e8-940e-78d5812b952d.png)

2018-05-11 19:02 UTC, bwinton requested changes

2018-05-11 19:02 UTC, bwinton commented on api/api.js
> +this.whimsyExp = class API extends ExtensionAPI {
We should probably name this `chromeUrlOverrides`, to match the manifest key.

2018-05-11 19:02 UTC, bwinton commented on api/api.js
> +        setNewtabOverride: async (shouldOverride) => {
Then this would be `enableNewtab`, with future additions possibly being `enableHistory`, and `enableBookmarks`…

2018-05-11 19:02 UTC, bwinton commented on manifest.json
> +  "experiment_apis": {
What will we do if this new API isn't available, like if we try to install it in Firefox Release, for instance?

2018-05-11 19:02 UTC, bwinton commented on settings/options.js
> +    newtabOverride: overrideNewtab.checked
I think we could collapse this down into a single value by using `'default'` for the non-overridden case…

2018-05-11 19:02 UTC, bwinton commented on settings/options.js
> +      document.querySelector("#mario").checked = result.mario;
Isn't this the same as:
```document.querySelector('#mario').checked = result.mario || true;```
?

2018-05-11 19:02 UTC, bwinton commented on settings/options.js
> +  function onError (error){
The spacing on this seems weird… I think it should be `function onError(error) {`, no?

2018-05-14 17:59 UTC, ericawright commented
We've decided to do this another way, closing.

2018-05-14 17:59 UTC, closed without merging